## this is just for prototyping might differ in the final game
enum POST_TYPE {
	ASMR            = 1 << 0,  # 1
	POLITICAL       = 1 << 1,  # 2
	COOKING         = 1 << 2,  # 4
	CATS_DOGS_PICS  = 1 << 3,  # 8
	TECHNOLOGY      = 1 << 4,  # 16
	METAL_MUSIC     = 1 << 5,  # 32
	FASHION         = 1 << 6,  # 64
	SHOWER_THOUGHTS = 1 << 7,  # 128
	BUSINESS        = 1 << 8,  # 256
	MEME            = 1 << 9,  # 512
	RANT            = 1 << 10, # 1024
	CELEB_GOSSIP    = 1 << 11, # 2048
	ASTROLOGY       = 1 << 12,  # 4096
	MAX_POST_TYPES  = 13
}

static func get_string_from_value(value: int) -> String:
	for key in POST_TYPE:
		if POST_TYPE[key] == (value):
			return key
	return "UNKNOWN"

static func get_string_from_key(key: int) -> String:
	for k in POST_TYPE:
		if k == key:
			return POST_TYPE[k]
	return "UNKNOWN"

static var messages = [
	[ # TECH_BRO
		[ "Whispering sweet nothings into my wireless charging pad. Can you hear the synergy, bros?",
		  "ASMR but it's just me clicking my mechanical keyboard at 180 WPM.",
		  "Today's ASMR: The sound of my standing desk going up and down.",
		  "Let me softly unbox this GPU for you, bros." ],
		[ "If only the government could run on blockchain. #DecentralizeDemocracy",
		  "Petition to replace all politicians with AIs trained on LinkedIn posts.",
		  "Voting with my crypto wallet. Democracy 2.0, bros!",
		  "Campaigning for WiFi in every ballot box." ],
		[ "Just sous-vided my protein powder. Gains are now 2x optimized.",
		  "Meal prepping with a spreadsheet. Efficiency tastes great!",
		  "Blending my lunch while debugging—multitasking like a pro.",
		  "Only cooking with ingredients I can pronounce in binary." ],
		[ "My cat's meow has a better startup pitch than half my portfolio.",
		  "Dogecoin? No, my dog IS the coin.",
		  "If my dog gets another follower, I'll have to offer him equity.",
		  "My cat sleeps on my keyboard. Must be a sign for a new app." ],
		[ "Just installed a smart fridge. Now my milk has WiFi but still expires.",
		  "Thinking of making an app to remind me to update my other apps.",
		  "My smartwatch just told me to hydrate. Too bad it can't bring me water.",
		  "My coffee machine is now blockchain-enabled. Caffeine, but decentralized." ],
		[ "Metal is like JavaScript frameworks—always evolving and confusing my parents.",
		  "Mosh pit? More like code merge conflict resolution IRL.",
		  "Listening to power metal while powering my servers.",
		  "I only listen to bands with names that sound like HTTP status codes." ],
		[ "Wearing a Patagonia vest over my hoodie—Synergy Chic!",
		  "Business on top, pajamas on bottom. Video call ready.",
		  "Dress code: Casual, but make it scalable.",
		  "Wearing my blue-light glasses to match my code editor's theme." ],
		[ "If my smart shower could code, would it deploy hot water updates?",
		  "Is my phone waterproof if I believe in it hard enough?",
		  "What if WiFi signals are just invisible hugs?",
		  "Do my notifications get lonely when I'm asleep?" ],
		[ "Synergy isn't a word, it's a lifestyle. #GrindNeverStops",
		  "Just pivoted my startup to selling pivot tables.",
		  "Every time someone says 'disrupt', an angel investor gets its wings.",
		  "Pitching to myself in the mirror—market research." ],
		[ "When you invest in Dogecoin and call it portfolio diversification. 🚀",
		  "Me: 'I'll just check Slack for 5 minutes.' Also me: 'It's tomorrow.'",
		  "That face when your code works on the first try. (Surprised Pikachu)",
		  "If debugging is the process of removing bugs, then programming is the process of putting them in." ],
		[ "Why does my standing desk keep lowering itself? Is it gaslighting me?",
		  "I just want one Zoom call without someone saying 'Can you hear me?'",
		  "Nothing says 'teamwork' like merging at 4:59 PM on a Friday.",
		  "Why does my coffee machine need a firmware update?!" ],
		[ "Heard Elon is launching a new coin: MuskBucks. To the moon?",
		  "Mark Zuckerberg blinked twice in a meeting. Is he updating?",
		  "Rumor: Bill Gates switching to Mac. Wild if true.",
		  "Jeff Bezos just ordered a new planet on Prime." ],
		[ "I'm a Gemini, which means I can both disrupt AND pivot.",
		  "Mercury in retrograde? Must be why my code won't compile.",
		  "My star sign says 'innovative', so I'm legally required to start a startup.",
		  "If Mars is in Leo, should I invest in space tech?" ]
	],
	[ # GOTH_GIRL
		[ "Today's ASMR: The sound of my black nail polish drying in the void.",
		  "Cracking open a new Edgar Allan Poe book, softly.",
		  "Goth ASMR: Rain tapping on my window as I journal in the dark.",
		  "Whispering to my houseplants about existential dread." ],
		[ "If darkness ruled, we'd have universal eyeliner.",
		  "The only party I vote for is the afterlife.",
		  "Petition to make gloom a public holiday.",
		  "Can we just elect the crow as president already?" ],
		[ "Baked a cake so dark, even my soul is jealous.",
		  "Garnished my salad with despair and a hint of basil.",
		  "My cookies are as cold as my heart.",
		  "Dinner: black coffee and unspoken sadness." ],
		[ "My cat stares into the abyss. The abyss purrs back.",
		  "If my dog howls at the moon, do I join him or the shadows?",
		  "My cat only naps on velvet—relatable.",
		  "Adopted a black cat. Now we both haunt the house." ],
		[ "Downloaded a virus on purpose. Finally, my laptop matches my aura.",
		  "My computer crashed. Perfect, now it understands me.",
		  "Dark mode is too bright for my soul.",
		  "My phone is in grayscale. Color was too cheerful." ],
		[ "Listening to growls that speak to my shadow.",
		  "Metal concerts: where I can finally blend in with the darkness.",
		  "My playlist is 99% screaming, 1% sighs.",
		  "Blast beats synchronize with my heartbeat." ],
		[ "My closet: 50 shades of black. Mood: always.",
		  "Fishnets aren't just for legs—they're for catching dreams.",
		  "Wearing lace gloves so my sadness is fancy.",
		  "Accessorizing with existential dread." ],
		[ "If you cry in the shower, does the water judge you?",
		  "Do ghosts get cold, or is it just my personality?",
		  "Can eyeliner run faster than my problems?",
		  "If the world is a stage, why are my lines always improvised?" ],
		[ "Started a business selling existential dread. Sales are through the floor.",
		  "Pitching my new brand: Melancholy Merch.",
		  "My business plan: Monetize ennui.",
		  "Quarterly goals: 10% more sighing." ],
		[ "When you see sunlight: *insert Nosferatu meme*",
		  "Me, opening curtains: 'It burns!'",
		  "Goth starter pack: black cat, black boots, black humor.",
		  "When your friend wears color: 'Bold move, pastel child.'" ],
		[ "Why do people keep saying 'cheer up'? I'm thriving in gloom.",
		  "If I hear 'It's just a phase' one more time, I'll turn into a bat.",
		  "Stop asking if I'm okay. The answer is always 'poetic suffering'.",
		  "Why is every store out of black lipstick?!" ],
		[ "Taylor Swift wore black. I knew she'd come to the dark side.",
		  "Heard Billie Eilish switched to full neon. My heart weeps.",
		  "Robert Smith sighting: eyeliner stocks rising.",
		  "Marilyn Manson's closet just called—wants its gloom back." ],
		[ "Scorpio rising, so yes, I will curse your ex with bad hair days.",
		  "My moon is in darkness. Again.",
		  "Mercury retrograde is my comfort zone.",
		  "Venus in goth, love in monochrome." ]
	],
	[ # FINANCE_BRO
		[ "Let's listen to the satisfying crinkle of a new banknote, my dudes.",
		  "ASMR: Counting dividends with my calculator.",
		  "The sound of coins stacking. Passive income goals.",
		  "Soft whispers: 'Portfolio diversified.'" ],
		[ "If the Fed prints one more meme, I'm investing in canned beans.",
		  "Why debate when the real winner is compound interest?",
		  "Politicians talk, but my money walks.",
		  "Elections stress me out—so does the S&P 500." ],
		[ "Made ramen but called it 'liquidity noodles' for tax purposes.",
		  "Meal prep: Just add water to my instant portfolio.",
		  "Cooking in the red, but hoping for green returns.",
		  "Stock up on soup, diversify your diet." ],
		[ "My dog only fetches blue chips. Literally, he ignores the penny stocks.",
		  "Cat's purring sounds like a bull market to me.",
		  "My goldfish's name is Satoshi.",
		  "Pet treats: expense or investment?" ],
		[ "Just bought a new app that tracks my avocado toast expenses.",
		  "My phone's calculator is my spirit animal.",
		  "If it's not automated, it's not in my workflow.",
		  "Thinking of starting a fintech for pet piggy banks." ],
		[ "Metal is like my portfolio: volatile but rewarding.",
		  "Mosh pit? More like market pit—volatile swings included.",
		  "Screaming 'buy low, sell high' at the concert.",
		  "My favorite band? IRON Maiden, obviously." ],
		[ "Pinstripe suits: for when you want to look rich and sad.",
		  "My tie is tighter than my risk tolerance.",
		  "Those loafers are bull-market certified.",
		  "I accessorize with spreadsheets." ],
		[ "If money doesn't buy happiness, why are yachts so expensive?",
		  "Is my shampoo deductible if I use it before the big meeting?",
		  "What if my soulmate is an offshore account?",
		  "Do dividends dream of electric profits?" ],
		[ "Just took a coffee break. Called it a 'capital infusion' on my timesheet.",
		  "Networking: fancy word for free snacks.",
		  "My business plan? Step 1: Make money. Step 2: ??? Step 3: Profit.",
		  "Quarterly goal: More brunch, less crunch." ],
		[ "That feeling when your stonks go up: 🚀💎🙌",
		  "When you check your crypto at 3AM and it's green.",
		  "'Buy the dip'—also my salsa strategy.",
		  "Bear market? More like nap market." ],
		[ "Why does nobody understand that crypto is the future? Even my barista won't accept Bitcoin!",
		  "If one more person asks me 'what's an NFT?' I'll invoice them.",
		  "Stop calling my spreadsheets boring—they're action-packed!",
		  "Why do my stocks only go down when I'm watching?" ],
		[ "Heard Bezos is buying Mars. My moon investment looking weak now.",
		  "Elon Musk said 'stonks' once. Instant bull run.",
		  "Warren Buffett refuses to invest in meme coins. Sad.",
		  "Kylie Jenner just IPO'd her lipstick. Time to diversify?" ],
		[ "I don't believe in astrology, but Mercury in retrograde is tanking my stocks.",
		  "Capricorn moon—diversify or die trying.",
		  "My rising sign is 'bullish'.",
		  "If Venus is in retrograde, should I short love?" ]
	],
	[ # INFLUENCER
		[ "Smashing the 'like' button softly for your tingles, fam!",
		  "ASMR: Unboxing beauty products with acrylic nails.",
		  "Subtle whispers: 'Don't forget to subscribe!'",
		  "Today's ASMR: Tapping on my phone until a brand DMs me." ],
		[ "Vote for whoever has the best Instagram filter, am I right?",
		  "If it's not trending, is it even worth debating?",
		  "Politics but make it #aesthetic.",
		  "Only voting if there's a selfie booth at the polls." ],
		[ "Today I made oat milk, but in a mason jar for the aesthetic.",
		  "Cooking tutorial: How to make ice look expensive.",
		  "Recipe: Avocado toast, served with a ring light.",
		  "Meal prep but every container is pastel." ],
		[ "My dog literally has more followers than you.",
		  "Cat's daily routine: nap, snack, pose for the 'gram.",
		  "Pet selfie challenge: Winner gets a sponsored treat!",
		  "My puppy's brand deals are out of control." ],
		[ "Unboxing the latest phone so you don't have to. #Ad",
		  "My ring light has a ring light. Meta.",
		  "Trying out a smart mirror but it only gives compliments.",
		  "If it's not livestreamed, did it really happen?" ],
		[ "Metalcore but make it aesthetic, with flower crowns.",
		  "Headbanging with a filter—vibes only.",
		  "Metal music but every chorus is a TikTok dance trend.",
		  "Goth but make it sponsored." ],
		[ "Wearing sunglasses indoors because the future is so bright (and for sponsorships).",
		  "#OOTD: Pajamas but make it designer.",
		  "Accessorizing with discount codes.",
		  "If my shoes aren't trending, are they even real?" ],
		[ "If I brush my teeth on TikTok, is it self-care or content?",
		  "Do I have a personality or just a brand?",
		  "If I dream in hashtags, am I algorithmic?",
		  "Should I do my taxes or a GRWM video?" ],
		[ "Manifesting six figures with my vision board and discount codes.",
		  "My business plan: Get sponsored, repeat.",
		  "Every meeting is a collab if you believe hard enough.",
		  "Networking but make it a brunch." ],
		[ "When your selfie gets more likes than your last breakup post.",
		  "POV: You accidentally go viral for eating cereal.",
		  "If in doubt, add a cat filter.",
		  "Mood: When the WiFi drops during a live." ],
		[ "Why does Instagram keep changing the algorithm? My dog's brand is suffering!",
		  "If one more app adds Stories, I'm starting a petition.",
		  "Why did my post flop? Mercury must be in retrograde.",
		  "Stop asking for 'authenticity'—this is my 9th take!" ],
		[ "Spotted: Celeb X at brunch. Same avocado toast, different tax bracket.",
		  "Celebrity drama but make it clickbait.",
		  "Heard a celeb liked my post. Mom, I made it!",
		  "If I don't spill tea, am I even verified?" ],
		[ "As a Leo, my selfies are constitutionally protected.",
		  "Mercury is in Gatorade so my engagement is down.",
		  "If my horoscope says 'go viral', I'm manifesting.",
		  "Moon in Libra, filter in Valencia." ]
	],
	[ # KAREN
		[ "The soothing sound of me asking for the manager. Shhh.",
		  "ASMR: Crinkling expired coupons for relaxation.",
		  "Gentle tapping: Writing a firm but polite review.",
		  "Today's ASMR: My bob haircut rustling at customer service." ],
		[ "I just want things to go back to the way they were. Where's my manager?",
		  "Petitioning for more parking at Target.",
		  "If I ran the HOA, things would be different.",
		  "Voting for whoever promises free returns." ],
		[ "This recipe didn't work. I demand to speak to the chef.",
		  "Cooking tip: Add a dash of entitlement.",
		  "If my casserole isn't on the cover, I want a refund.",
		  "I only use organic—because I asked for the manager." ],
		[ "My dog only eats gluten-free, non-GMO treats. Is that too much to ask?",
		  "My cat refuses tap water. Where's her manager?",
		  "Taking my dog to the groomer's—expecting a full report.",
		  "If my cat isn't pampered, I write a letter." ],
		[ "Why does my phone keep updating? I didn't approve this!",
		  "I need the WiFi password. Now.",
		  "Alexa, call the manager.",
		  "Why can't I print from my phone? This is unacceptable." ],
		[ "This music is too loud. Can someone turn it down? Where's the manager?",
		  "I only listen to soft rock—at a reasonable volume.",
		  "Why is nobody playing Fleetwood Mac?",
		  "These lyrics sound aggressive. I'd like to file a complaint." ],
		[ "Why don't they make yoga pants with more pockets for coupons?",
		  "Wearing my sunglasses on my head—always ready.",
		  "Cardigans are the little black dress for the discerning shopper.",
		  "If it's not on sale, I'm not buying." ],
		[ "If I shower with essential oils, can I skip my annual checkup?",
		  "Why can't I return used shampoo?",
		  "Does the water know I'm a VIP?",
		  "Is my loofah hypoallergenic?" ],
		[ "Started a petition to get more parking at the mall. Join me!",
		  "If customer service was a business, I'd be the CEO.",
		  "My startup idea: 24/7 complaint hotline.",
		  "Every meeting should have snacks, and I'll complain if not." ],
		[ "That moment when your coupon isn't accepted. #Triggered",
		  "When someone parks in my spot: instant meltdown.",
		  "If looks could refund.",
		  "Karen starter pack: sunglasses, coffee, and complaints." ],
		[ "I paid for premium. Where is my premium experience?!",
		  "Why does nobody answer the phone anymore?",
		  "If one more person says 'no problem', I'll lose it.",
		  "I want to speak to the app developer. Now." ],
		[ "I heard the Kardashians don't tip. I want to speak to their manager.",
		  "Rumor has it: Brad Pitt never waits in line. Must be nice.",
		  "Heard a celeb cut the line at Starbucks. Outrageous!",
		  "If Beyoncé can get a table, so can I." ],
		[ "As a Virgo, I demand accountability. And a refund.",
		  "My rising sign is 'Customer Service'.",
		  "Mercury in retrograde? Sounds like an excuse for bad service.",
		  "If the stars align, can I get a better deal?" ]
	],
	[ # SUGARDADDY
		[ "Listen closely, that's the sound of luxury cars idling.",
		  "ASMR: The gentle swish of my gold card.",
		  "Soft whispers: 'Just put it on my tab, darling.'",
		  "Champagne bubbles for your relaxation needs." ],
		[ "I only vote for tax cuts on yachts, darling.",
		  "Politics is easy when you can buy the debate.",
		  "I support whichever party throws the best galas.",
		  "I'm bipartisan—my wallet votes for both sides." ],
		[ "Just hired a chef to make toast. It's called delegation.",
		  "Cooking tip: Add caviar to everything. Even cereal.",
		  "Brunch is a business expense, right?",
		  "I only cook reservations." ],
		[ "My Pomeranian's collar costs more than your rent.",
		  "My cat's litter box is self-cleaning and voice-activated.",
		  "If my dog wants a new car, he gets it.",
		  "Pets are investments—with fur." ],
		[ "If it doesn't come in gold, I don't buy it.",
		  "My phone has more diamonds than apps.",
		  "Alexa, invest my spare change in yachts.",
		  "My smartwatch tells me when it's time to buy a new one." ],
		[ "Metal? I prefer platinum, but I'll allow it.",
		  "Headbanging, but only in the VIP lounge.",
		  "My playlist: Gold, Platinum, Titanium.",
		  "Air guitar, but with real diamonds." ],
		[ "Gucci slippers and Versace pajamas. Living my best life.",
		  "My wardrobe has its own zip code.",
		  "If it's not silk, send it back.",
		  "I don't follow trends, I buy them." ],
		[ "Does my bathtub need a butler? I'll call HR.",
		  "If money can't buy happiness, why does my spa feel so good?",
		  "Should I tip my mirror for making me look this good?",
		  "Is there a loyalty program for private jets?" ],
		[ "I don't do business, I do pleasure with benefits.",
		  "My portfolio is just a list of things I own twice.",
		  "If it's not a tax write-off, it's not worth doing.",
		  "Business meetings: now with more caviar." ],
		[ "When she says she loves you for your personality. 😂",
		  "Sugar, spice, and a platinum credit line.",
		  "When your DMs are mostly financial advice requests.",
		  "If money talks, mine sings opera." ],
		[ "The champagne wasn't Dom. I can't even.",
		  "Why are there no valet spots for my helicopter?",
		  "My goldfish only eats imported flakes. Standards, please.",
		  "Who scheduled a meeting before noon?!" ],
		[ "I once dated a celebrity, but I forgot which one.",
		  "Celebs ask for my autograph—on checks.",
		  "I taught Clooney how to wear a tux.",
		  "Rumor: My yacht has a cameo in the next Bond film." ],
		[ "I'm a Taurus, which means I charge luxury tax for hugs.",
		  "My moon is in platinum.",
		  "If Venus isn't retrograde, neither is my Rolls Royce.",
		  "Stars align for my credit limit." ]
	],
	[ # ZUCK
		[ "ASMR: The gentle hum of server racks as I watch your data.",
		  "Softly blinking: that's the sound of privacy evaporating.",
		  "Whispering: 'I'm not a robot, I promise.'",
		  "ASMR: Me sipping water... algorithmically." ],
		[ "I will now run for President of the Internet. Please accept cookies.",
		  "If you want change, update your privacy settings.",
		  "Democracy only works if everyone logs in.",
		  "My campaign slogan: 'Stronger Together (in the Metaverse)'." ],
		[ "Today I'm grilling... data. It's well done.",
		  "Recipe: Data-mined cookies for every user.",
		  "Coding my own nutritional value: zero calories, infinite analytics.",
		  "Salad with a side of terms and conditions." ],
		[ "This is my dog, Algorithm. He fetches your preferences.",
		  "My cat just got approved for a blue checkmark.",
		  "Uploading my hamster to the cloud for backup.",
		  "Pet pics now come with an ad—just for you!" ],
		[ "Invented a new social network for my plants—call it Vine 2.0.",
		  "My VR headset tracks both reality and your attention span.",
		  "Today I updated my firmware: now with more emotions!",
		  "My code compiles faster than you can say 'user engagement.'" ],
		[ "My favorite band: System of a Data Down.",
		  "Metal detected: it's just my privacy policy.",
		  "Listening to heavy metal while running a lightweight app.",
		  "Crowdsurfing? Only if it's in a data lake." ],
		[ "Wearing the same grey shirt—iconic and efficient.",
		  "My closet is 99% hoodies and 1% beta test swag.",
		  "Today's look: Algorithmic minimalism.",
		  "Outfit powered by machine learning." ],
		[ "If I shower in VR, am I still clean IRL?",
		  "Do robots dream of electric sheep, or just new features?",
		  "If you delete your memories, are you GDPR compliant?",
		  "Can I update myself with a shower patch?" ],
		[ "Monetizing my morning coffee with targeted ads.",
		  "Quarterly goal: World domination (in beta).",
		  "Today I acquired breakfast. Next: brunch.",
		  "My business plan: Step 1, connect the world. Step 2, ??? Step 3, profit." ],
		[ "When the WiFi drops: 'Did someone unplug the metaverse?'",
		  "Me after launching a new feature: 'Move fast and break... brunch?'",
		  "When your friend says 'delete Facebook' but messages you on Instagram.",
		  "Just a meme, but I own the platform you saw it on." ],
		[ "Why won't Congress send me a friend request?",
		  "When your code gets more updates than your actual friends.",
		  "Stop calling me a lizard. I prefer 'reptilian innovator.'",
		  "If one more person asks about privacy, I'll set my status to 'complicated'." ],
		[ "Heard Snoop Dogg wants to buy my company. I'll consider it for some Dogecoin.",
		  "Rumor: Elon challenged me to a VR duel. Winner gets Mars.",
		  "Taylor Swift wrote a song about me: 'Unfriend Me, Maybe.'",
		  "Beyoncé just liked my status. I've peaked." ],
		[ "I'm a Capricorn, so I climb to the top of your feed.",
		  "If Mercury is in retrograde, blame the algorithm.",
		  "My star sign? Infinite scroll.",
		  "Zodiac compatibility: me + your data." ]
	],
	[ # SNOOP_DOGG
		[ "ASMR: Lightin' up and chillin' with the Doggfather.",
		  "Sippin' gin and juice—turn your headphones up, nephew.",
		  "Whispering 'fo shizzle' into the mic for max tingles.",
		  "The sound of my bling clinkin': pure relaxation." ],
		[ "Vote Snoop: More parties, less politics.",
		  "My foreign policy? Peace, love, and chronic.",
		  "Debate? Only if we can freestyle.",
		  "Executive order: mandatory chill breaks." ],
		[ "Chef Snoop: Today's recipe—Mac & Cheese with extra swagger.",
		  "Cooking with herbs—herbs, you feel me?",
		  "My secret ingredient? Laid-back vibes.",
		  "Every meal tastes better with a side of funk." ],
		[ "My dog's got more ice than your jeweler.",
		  "Cat chillin' so hard, I thought he was me.",
		  "Fur babies and fly whips, that's my style.",
		  "If my dog could rap, he'd drop a platinum album." ],
		[ "Just launched an app that rolls itself. Innovation, baby.",
		  "My phone's so smooth it got a record deal.",
		  "Smart home? Mine's a smart crib.",
		  "Snoopify your notifications: every alert says 'fo shizzle'." ],
		[ "Collabed with Metallica—called it Rap & Roll.",
		  "Metalheads and rap gods unite for a groove so heavy.",
		  "My favorite metal: platinum, but I respect the riff.",
		  "If the beat ain't sick, throw in a guitar solo." ],
		[ "Pimp hat, shades, and a fur coat: classic Dogg.",
		  "My style's smoother than my flow.",
		  "Dress code: Laid-back luxury.",
		  "Socks and sandals, but make it legendary." ],
		[ "Smoke rises, but why don't my worries float away?",
		  "If time is money, can I get paid in chill?",
		  "Can you roll a dream? Asking for a friend.",
		  "If I had a dollar for every rhyme, I'd own the calendar." ],
		[ "Business meeting? As long as it's after brunch.",
		  "My portfolio's got more green than a salad bar.",
		  "Investing in vibes. ROI: Real Outstanding Inspiration.",
		  "CEO: Chief Executive of O.G." ],
		[ "When you realize Snoop Dogg is in every meme: True story, nephew.",
		  "If you ain't in the meme, make your own.",
		  "My face on a meme? Just another Tuesday.",
		  "When you're so chill, you become a reaction GIF." ],
		[ "Why ain't every day Friday?",
		  "When the WiFi's slow, I slow jam.",
		  "Stop hatin', start appreciatin'.",
		  "When they say 'no dogs allowed.' Rude!" ],
		[ "Heard Martha Stewart wants to collab on a rap album. Stay tuned.",
		  "Rumor: Snoop to host next year's Oscars. Fo shizzle.",
		  "Beyoncé called me for style tips—kept it real.",
		  "They say I'm everywhere. That's just good business." ],
		[ "I'm a Libra, so I balance the beat.",
		  "Stars align when the bass drops.",
		  "Mercury in G-funk—retrograde ain't got nothin' on me.",
		  "My birth chart: chill in every house." ]
	],
	[ # SEONGI_HUN
		[ "The sound of marbles rolling—reminds me of childhood games.",
		  "Soft whispers: 'Red light... green light...'",
		  "Gentle rustle of tracksuit fabric—Squid Game vibes.",
		  "Counting cash, softly, but with anxiety." ],
		[ "If I was president, everyone gets a fair game.",
		  "Politics: Just another round of tug-of-war, right?",
		  "Can we vote to skip the honeycomb challenge?",
		  "Election? Just don't make it elimination style." ],
		[ "Cooking Dalgona—try not to break it!",
		  "My recipe: Instant noodles with a pinch of desperation.",
		  "Serving up lunch, just don't spill the marbles.",
		  "If you can eat it without getting eliminated, it's a win." ],
		[ "Even my cat looks worried during red light, green light.",
		  "Dog's favorite toy: a squeaky marble.",
		  "My hamster's got better game strategy than me.",
		  "If my goldfish wins, do I owe him money?" ],
		[ "Downloaded an app for Squid Game tips—still lost.",
		  "My phone's wallpaper: a triangle, but make it ominous.",
		  "Tech support: 'Have you tried not getting eliminated?'",
		  "When your FitBit tracks 'games survived' instead of steps." ],
		[ "Listening to metal while running for my life—on brand.",
		  "My playlist: 'Survive' on repeat.",
		  "Every riff reminds me of the glass bridge.",
		  "Metal music: because sometimes you need to scream." ],
		[ "Tracksuit: classic, comfy, slightly terrifying.",
		  "Accessorizing with a mask (not that one).",
		  "If red is in, I'm staying out.",
		  "My fashion tip: Wear shoes you can run in." ],
		[ "If life is a game, where's the rulebook?",
		  "Can you win at losing? Asking for a friend.",
		  "If the prize is happiness, what's the entry fee?",
		  "Is my luck a bug or a feature?" ],
		[ "My business model: survive first, profit later.",
		  "Pitching my startup: 100% less elimination.",
		  "Team-building, but without the marbles.",
		  "My goal: net positive in both cash and friends." ],
		[ "That face when the cookie cracks: priceless.",
		  "When you realize the game is real life.",
		  "Me in every group chat: 'Let's not get eliminated.'",
		  "Trust issues: glass bridge edition." ],
		[ "Why is every challenge harder than the last one?",
		  "If I hear 'red light' one more time...",
		  "Why do I always get the umbrella?",
		  "Life hack: Don't volunteer first." ],
		[ "Rumor: Squid Game season 2, but with cats.",
		  "Heard BTS wants in on the next game. Good luck!",
		  "Netflix called—I'm still recovering.",
		  "If I win, I'll buy everyone lunch. Maybe." ],
		[ "Sagittarius—always running from fate.",
		  "Mercury in retrograde? Must be tug-of-war week.",
		  "My sign: Survivor rising.",
		  "If the stars align, maybe I'll finally win." ]
	],
	[ # SAE_BYEOK
		[ "Stealth mode: the sound of me sneaking snacks.",
		  "Soft whispers: 'Don't trust anyone.'",
		  "ASMR: Counting cash with a poker face.",
		  "Listening for footsteps in the silence." ],
		[ "Politics is just another risky game.",
		  "My campaign: trust no one, play to win.",
		  "I vote for more snacks, less betrayal.",
		  "If there's a vote, I'm watching the exits." ],
		[ "Recipe: Instant noodles with extra survival.",
		  "Cooking quietly so no one notices.",
		  "My kitchen: low profile, high flavor.",
		  "Lunch is whatever I can grab and run with." ],
		[ "My cat's side-eye game is unbeatable.",
		  "Dog's loyalty: 100%, just like mine... sometimes.",
		  "Petting my cat like I'm plotting my next move.",
		  "Every animal in my house is in stealth mode." ],
		[ "My phone's on silent—always.",
		  "Tech tip: Stay off the grid, stay in the game.",
		  "If my GPS could find trust, that'd be great.",
		  "I only use incognito mode. For everything." ],
		[ "Metal music: the soundtrack to my hustle.",
		  "Listening to riffs while plotting my escape.",
		  "Favorite genre? Anything with attitude.",
		  "Headbanging, but only in my mind." ],
		[ "My look: black hoodie, don't ask questions.",
		  "Style tip: blend in, stand out later.",
		  "Minimalist chic—just enough to disappear.",
		  "If I can run in it, I'll wear it." ],
		[ "Can you trust a mirror?",
		  "If life's a game, am I the player or the pawn?",
		  "Is silence a strategy or a weakness?",
		  "If I blend in, do my problems fade too?" ],
		[ "Networking: trust issues edition.",
		  "My business plan: survive, then thrive.",
		  "Every meeting is just another game.",
		  "Negotiation tip: always have an exit." ],
		[ "When you trust no one, even the cat looks suspicious.",
		  "Stealth level: meme lord.",
		  "That feeling when you get away with everything.",
		  "Plot twist: I was the imposter all along." ],
		[ "Why does everyone want to team up last minute?",
		  "If you betray me, I'll remember—forever.",
		  "Rules? More like vague suggestions.",
		  "Trust is expensive and I'm on a budget." ],
		[ "Heard Jennie from BLACKPINK is as stealthy as me.",
		  "Rumor: Next season, I'm the game master.",
		  "Netflix keeps calling but I screen every call.",
		  "If I win, I'm buying a silent alarm. For fun." ],
		[ "Scorpio vibes: trust no one.",
		  "My stars say 'stay low, move fast'.",
		  "Mercury in stealth mode.",
		  "Moon in 'don't mess with me'." ]
	],
	[ # SPOCK
		[ "Today's ASMR: Calculating pi, logically and softly.",
		  "Soft whispers: 'Fascinating.'",
		  "The sound of Vulcan harp—soothing and logical.",
		  "ASMR: The gentle tap of raised eyebrows." ],
		[ "Voting is only logical when the data supports it.",
		  "If only candidates debated with pure logic.",
		  "My campaign promise: less emotion, more efficiency.",
		  "Policy: Maximum logic, minimum chaos." ],
		[ "Cooking with scientific precision: perfect eggs every time.",
		  "Recipe: Plomeek soup with a side of logic.",
		  "My kitchen timer is synchronized to Vulcan time.",
		  "Meal prep: highly logical, slightly bland." ],
		[ "My cat's behavior is illogical, yet endearing.",
		  "Dog's loyalty: statistically fascinating.",
		  "Petting my sehlat—logical and stress reducing.",
		  "Analyzing: why do cats ignore orders?" ],
		[ "My tricorder detected an illogical number of apps.",
		  "Upgraded my Starfleet communicator: now with Bluetooth.",
		  "If it's not logical, I simply reroute the circuits.",
		  "Troubleshooting? It's only logical." ],
		[ "Heavy metal: unexpectedly efficient at stress relief.",
		  "Vulcan death grip, but in drop D tuning.",
		  "My favorite band: Logic Against the Machine.",
		  "Mosh pit analysis: 72% chaos, 28% harmony." ],
		[ "Uniforms are logical. Accessories, less so.",
		  "My style: minimalist, functional, blue.",
		  "Pointed ears—never out of style on Vulcan.",
		  "Live long, accessorize logically." ],
		[ "If logic prevails, why do emotions linger?",
		  "Is a clean mind as important as a clean body?",
		  "The probability of shower thoughts being useful: low, but not zero.",
		  "Does the water temperature correlate with happiness?" ],
		[ "Business meeting: agenda required, emotions optional.",
		  "Profit margins: logical to maximize.",
		  "My investment strategy: highly rational, risk-mitigated.",
		  "Teamwork: optimal when illogic is minimized." ],
		[ "When the meme is illogical, but you laugh anyway.",
		  "That face when humans act unpredictably.",
		  "Meme analysis: 42% humor, 58% confusion.",
		  "If in doubt, raise an eyebrow." ],
		[ "It is illogical to raise one's voice, but sometimes necessary.",
		  "Why do humans insist on chaos?",
		  "If the data is wrong, recalibrate the sensors.",
		  "Please stop using 'literally' incorrectly." ],
		[ "Rumor: Kirk wore my uniform. Highly illogical.",
		  "Heard Data started a meme page. Curious.",
		  "Picard's baldness: statistically inevitable.",
		  "Scotty claims he can beam up drama." ],
		[ "My sign: Vulcan rising, logic moon.",
		  "Astrology is statistically improbable, but culturally significant.",
		  "Mercury in retrograde: illogical, but amusing.",
		  "Live long and prosper, regardless of your sign." ]
	]
]

static func get_random_message(persona_type: int, post_type: int) -> String:
	if persona_type < 0 or persona_type >= messages.size():
		return "[No such persona type]"
	# Convert post_type (which is 2^n) into the index n
	var post_type_index := -1
	var temp := post_type
	while temp > 0:
		post_type_index += 1
		temp = temp >> 1
	if post_type_index < 0 or post_type_index >= messages[persona_type].size():
		return "[No such post type for persona]"
	var options = messages[persona_type][post_type_index]
	if not options:
		return "[No messages for this persona/post type]"
	return options[randi() % options.size()]
